defaults:
  ignoreError: true
  markup: pango
  color: "#b4bab4"

blocks:
- type: module
  module: "/home/cdowner/projects/ty3status-module-countdown-to-date/lib/index.js"
  interval: 1
  params:
    endDate: 2019-04-12T23:00:00

- type: module
  module: battery
  interval: 300
  params:
    chargingIcon: C
    dischargingIcon: D
    chargedIcon: G
    fontAwesome: false
    urgentLevel: 10

- type: module
  module: cpu-usage
  interval: 5

- type: module
  module: memory
  interval: 30

- type: module
  module: datetime
  align: center